version: '3.8'

services:
  app:
    build: .
    container_name: app
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nqueens_db
      - POSTGRES_USER=user
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nqueens_db
      POSTGRES_USER: user
    ports:
      - "5432:5432"