name: FastAPI
on:
  push:
    branches: [ 'main', 'feature/**']
    tags: [ 'v*']
jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install 
        run: pip install requirements.txt
